# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        include:
          - experimental: false
          - python-version: "3.12"
            experimental: true
    defaults:
      run:
        shell: /bin/bash --noprofile --norc -exo pipefail {0}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: MatteoH2O1999/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: ${{ matrix.experimental }}

    - name: Show python and git versions
      run: |
        python --version
        git version

    - name: Prepare this repo for tests
      run: |
        TRAVIS=yes ./init-tests-after-clone.sh

    - name: Prepare git configuration for tests
      run: |
        git config --global user.email "travis@ci.com"
        git config --global user.name "Travis Runner"
        # If we rewrite the user's config by accident, we will mess it up
        # and cause subsequent tests to fail
        cat test/fixtures/.gitconfig >> ~/.gitconfig

    - name: Update PyPA packages
      run: |
        python -m pip install --upgrade pip
        if pip freeze --all | grep --quiet '^setuptools=='; then
            # Python prior to 3.12 ships setuptools. Upgrade it if present.
            python -m pip install --upgrade setuptools
        fi
        python -m pip install --upgrade wheel

    - name: Install project and test dependencies
      run: |
        pip install ".[test]"

    - name: Check types with mypy
      run: |
        mypy -p git
      # With new versions of mypy new issues might arise. This is a problem if there is nobody able to fix them,
      # so we have to ignore errors until that changes.
      continue-on-error: true

    - name: Test with pytest
      run: |
        pytest
      continue-on-error: false

    - name: Documentation
      run: |
        pip install -r doc/requirements.txt
        make -C doc html
